name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
  REGISTRY: docker.io
  IMAGE_NAME: flaskapp
  DOCKERHUB_TOKEN: "${{ secrets.DOCKER_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa martin@54.227.77.204 << 'EOF'
          if [ ! -d /home/martin/app ]; then
            mkdir -p /home/martin/app
          fi
          cd /home/martin/app
          if [ -d .git ]; then
            git pull
          else
            git clone https://github.com/MartinM-17/docker-mysql-nginx-flask-cicd.git .
          fi
          docker-compose down
          docker-compose pull
          docker-compose up -d
          EOF
