name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
  REGISTRY: docker.io
  IMAGE_NAME: flaskapp
  DOCKERHUB_TOKEN: "${{ secrets.DOCKER_PASSWORD }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build & Test
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .
    
      - name: Determine Environment
        id: Determine_env
        run: |
            if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
              echo "::set-output name=env::prod"
            elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
              echo "::set-output name=env::staging"
            else
              echo "::set-output name=env::dev"
            fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH to EC2 and deploy
        run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa martin@54.90.85.153 << 'EOF'
        mkdir -p /home/martin/app
        cd /home/martin/app
        if [ ! -f docker-compose.yml ]; then
          echo "docker-compose.yml is missing. Exiting."
          exit 1
        fi
        docker-compose down
        docker-compose pull
        docker-compose up -d
      EOF
